load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "sync_proto",
    srcs = ["sync.proto"],
)

proto_library(
    name = "display_proto",
    srcs = ["display.proto"],
)

proto_library(
    name = "screenshot_proto",
    srcs = ["screenshot.proto"],
)

build_test(
    name = "proto_build_test",
    targets = [
        ":sync_proto",
        ":display_proto",
        ":screenshot_proto",
    ],
)

py_proto_library(
    name = "sync_py_proto",
    deps = [":sync_proto"],
)

py_proto_library(
    name = "display_py_proto",
    deps = [":display_proto"],
)

py_proto_library(
    name = "screenshot_py_proto",
    deps = [":screenshot_proto"],
)

py_test(
    name = "codegen_test",
    srcs = ["codegen_test.py"],
    deps = [
        ":sync_py_proto",
        ":display_py_proto",
        ":screenshot_py_proto",
    ],
)
